# Generated by Django 4.0.1 on 2022-02-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='imagen',
            new_name='image',
        ),
    ]
