# Generated by Django 4.0.1 on 2022-02-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_imagen_cuenta_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='image',
            field=models.ImageField(default='papaCal.png', upload_to='profile_pics'),
        ),
    ]
